#!/usr/bin/env node
/* ===========================================================================
   ONE POINT OH: THE FIRST BUILD'S PAGE — `node scripts/opo-build.mjs`
   (ONE-POINT-OH-PLAN.md, "How the copy runs", Phase 1)

   ONE POINT OH wants the game back the way it was the day he arrived: the
   first upload, 3af8b6d (7 Aug 2026). While he holds a profile, the page
   boots into that build, hosted in a frame of the game's own. This writes it,
   once, from git, to onepointoh/first.html:

     · the first build's page as committed, and its script byte for byte
     · ONE POINT OH's own scripts around it: onepointoh/seal.js before the
       script, onepointoh/lock.js after it
     · a Content-Security-Policy in its head that lets nothing load from
       anywhere but this site (the third seal: Fireproof, from esm.sh)

   The game's Worker has no build step, so the page is committed, unlike
   PvP's (scripts/pvp-build.mjs). It never needs making again: the first
   build does not change. Run it with --check (npm run test:opo does) to hold
   the committed page to the commit, byte for byte.

   As committed, the first build would do harm here. The seals (seal.js):
     1. it saves under today's key, voidrunner_save_v1, and its merge keeps
        nine fields: a sync would strip a modern save. It is given keys of its
        own, and may write nothing else.
     2. it posts runs to /api/leaderboard, today's Worker. The post never
        leaves the frame: its top five is the lock's own runs.
     3. it loads Fireproof from esm.sh. The page's policy refuses it, so it
        keeps to the browser, as it always did offline.
   ========================================================================= */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const PAGE = join(ROOT, 'onepointoh', 'first.html');
// the first upload, and the path it was uploaded at (it moved to the root unchanged in 7941a2d)
export const FIRST = '3af8b6d';
export const FIRST_PATH = 'game/index.html';
/* What it is, so the page can be held to it on a checkout with no history
   (a shallow clone): the whole file, and the script alone. */
export const FIRST_SHA = 'ab1ebe7c1ab6bdf2c60e172a23625bd02b20f0a0cfd8a8902dec184d8371e7ad';
const sha = s => createHash('sha256').update(s, 'utf8').digest('hex');

// the policy: this site's own scripts and the page's inline one; nothing fetched or loaded from anywhere else
export const CSP = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; " +
                   "connect-src 'self'; img-src 'self' data: blob:; font-src 'self' data:; frame-src 'none'; " +
                   "object-src 'none'; base-uri 'none'; form-action 'none'";

// the first build's one script, exactly as it stands between its tags
export function scriptOf(html) {
  const m = /<script>([\s\S]*?)<\/script>/.exec(html);
  if (!m) throw new Error('opo-build: no script in the first build');
  return m[1];
}

export function buildFirst(html) {
  if (sha(html) !== FIRST_SHA) throw new Error('opo-build: that is not the first build (sha256 ' + sha(html) + ')');
  const head = '<meta charset="utf-8">\n';
  const open = '<canvas id="c"></canvas>\n<script>\n';
  const close = '</script>\n</body>';
  for (const [s, what] of [[head, 'its charset'], [open, 'its script'], [close, 'its end']])
    if (html.split(s).length !== 2) throw new Error('opo-build: the first build no longer has ' + what + ' where it was expected');
  return html
    .replace('<!doctype html>\n', '<!doctype html>\n<!-- GENERATED by scripts/opo-build.mjs from ' + FIRST + ':' + FIRST_PATH +
             ' (the first upload, 7 Aug 2026). Do not edit: the script below is that build\'s, byte for byte. -->\n')
    .replace(head, head + '<meta http-equiv="Content-Security-Policy" content="' + CSP + '">\n')
    .replace(open, '<canvas id="c"></canvas>\n<!-- ONE POINT OH\'s seal: runs first (onepointoh/seal.js) -->\n' +
                   '<script src="seal.js"></script>\n<script>\n')
    .replace(close, '</script>\n<!-- and the hooks into it (onepointoh/lock.js) -->\n<script src="lock.js"></script>\n</body>');
}

// the first build, from git; null on a checkout without it
export function firstFromGit() {
  try { return execFileSync('git', ['show', FIRST + ':' + FIRST_PATH], { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }); }
  catch (e) { return null; }
}

/* The committed page against the commit: its script the first build's byte
   for byte, and the page what this script makes. Returns a list of problems. */
export function checkPage(page) {
  const out = [];
  if (!page) return ['onepointoh/first.html is missing: run node scripts/opo-build.mjs'];
  const scripts = [...page.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]);
  if (scripts.length !== 1) out.push('the page has ' + scripts.length + ' inline scripts, not the first build\'s one');
  const git = firstFromGit();
  if (git !== null) {
    if (sha(git) !== FIRST_SHA) out.push(FIRST + ' in git is not the first build this script knows');
    else {
      if (scripts[0] !== scriptOf(git)) out.push('the script is no longer ' + FIRST + '\'s byte for byte');
      if (page !== buildFirst(git)) out.push('the page is not what scripts/opo-build.mjs makes from ' + FIRST);
    }
  } else {
    // no history here: hold the script to what it hashed to when it was made
    const want = createHash('sha256').update(scripts[0] || '', 'utf8').digest('hex');
    if (want !== FIRST_SCRIPT_SHA) out.push('the script is no longer the first build\'s byte for byte (sha256 ' + want + ')');
  }
  return out;
}
// the first build's script alone, hashed (for a checkout with no history)
export const FIRST_SCRIPT_SHA = 'da5b49589e262b302dca7ca4de938af8f09e8700a73f2a6786db181f8e64bf3b';

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  if (check) {
    const page = existsSync(PAGE) ? readFileSync(PAGE, 'utf8') : null;
    const bad = checkPage(page);
    if (bad.length) { for (const b of bad) console.log('opo-build: ' + b); process.exit(1); }
    console.log('opo-build: onepointoh/first.html is ' + FIRST + '\'s script, byte for byte' + (firstFromGit() === null ? ' (by its hash: no history here)' : ''));
    process.exit(0);
  }
  const git = firstFromGit();
  if (git === null) { console.log('opo-build: ' + FIRST + ' is not in this checkout (git fetch --unshallow)'); process.exit(1); }
  const page = buildFirst(git);
  mkdirSync(dirname(PAGE), { recursive: true });
  writeFileSync(PAGE, page);
  console.log('opo-build: wrote onepointoh/first.html (' + Math.round(page.length / 1024) + ' KB), script sha256 ' +
              createHash('sha256').update(scriptOf(git), 'utf8').digest('hex'));
}
