/* ===========================================================================
   THE PVP ENGINE TEST — part of `npm run test:pvp` (PVP-PLAN.md, Phase 3)

   PvP's play page is the game's own engine, copied at deploy with PvP's
   scripts in front (scripts/pvp-build.mjs). This plays that page in plain
   Node (scripts/lib/game-vm.mjs) and holds it to its promise: the engine
   boots sealed, asks no server for anything and loads no script, flies the
   account's pilot with its awake form and reward upgrades, and spawns
   nothing. The same engine booted as the game, beside it, shows the recorder
   would have caught a request. Then a match: two copies, host and guest,
   linked the way scripts/lockstep.mjs links two games, each flown by a bot,
   from the handshake through the host's start to one of them leaving. Each
   engine talks to PvP's own Worker and its referee (the Match object) as its
   own signed-in player, on a SQLite D1, and the match ends recorded.
   ========================================================================= */
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadGame, gameScript } from './lib/game-vm.mjs';
import { buildPlay, PVP_SCRIPTS } from './pvp-build.mjs';
import { randomBytes } from 'node:crypto';
import { makeD1 } from './lib/d1-sqlite.mjs';
import { makeNamespace } from './lib/do-fake.mjs';
const pvpWorker = (await import('../pvp/src/index.js')).default;
const { Match, Matchmaker } = await import('../pvp/src/objects.js');
const { ensurePvp } = await import('../pvp/src/records.js');
const { seasonOf } = await import('../src/season.js');
const { ensureAuth, sha256 } = await import('../src/auth.js');

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const IDX = join(ROOT, 'index.html');
const SITE = join(ROOT, 'pvp', 'site');

let fails = 0, passes = 0;
function ok(cond, what, extra) {
  if (cond) { passes++; return; }
  fails++;
  console.log('  FAIL  ' + what + (extra !== undefined ? '  ' + JSON.stringify(extra).slice(0, 300) : ''));
}
const section = t => console.log('· ' + t);
const t0 = Date.now();

/* ---------------------------------------------------------------------- */
section('the play page, made from the game');
const html = readFileSync(IDX, 'utf8');
const page = buildPlay(html);
{
  const engine = gameScript(IDX).code;
  const scripts = [...page.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]);
  ok(scripts.length === 1, 'one inline script: the engine (the www redirect is gone)', scripts.length);
  ok(scripts[0] === engine, 'the engine, byte for byte');
  ok(!/google-adsense-account/.test(page), 'no AdSense tag');
  ok(/<title>VOIDRUNNER · PvP<\/title>/.test(page), 'its own title');
  const at = page.indexOf('<script>\n"use strict"');
  const srcs = [...page.matchAll(/<script src="([^"]+)"><\/script>/g)];
  ok(srcs.map(m => m[1]).join() === PVP_SCRIPTS.join() && srcs.every(m => m.index < at), 'PvP\'s scripts, in order, before the engine', srcs.map(m => m[1]));
  ok(/GENERATED by scripts\/pvp-build\.mjs/.test(page), 'marked as made, not written');
  let threw = null;
  try { buildPlay(html.replace('google-adsense-account', 'something-else')); } catch (e) { threw = e; }
  ok(threw && /AdSense/.test(threw.message), 'a game page it no longer recognises stops the build', String(threw));
}

/* A browser that writes down every request, and every script it is asked to load. */
function recorder(win) {
  win.__net = [];
  win.fetch = (u) => { win.__net.push('fetch ' + String(u)); return Promise.reject(new Error('offline')); };
  const make = win.document.createElement;
  win.document.createElement = tag => {
    const el = make(tag);
    if (String(tag).toLowerCase() === 'script') {
      let src = '';
      Object.defineProperty(el, 'src', { get: () => src, set: v => { src = v; win.__net.push('script ' + v); } });
    }
    return el;
  };
}
/* And enough more DOM for PvP's waiting room (match.js): an element finds
   what its innerHTML would have held, one stand-in per selector. */
function rooms(win) {
  const make = win.document.createElement;
  win.document.createElement = tag => {
    const el = make(tag);
    const q = {};
    el.querySelector = sel => q[sel] || (q[sel] = { textContent: '', hidden: false, addEventListener() {},
                                                    classList: { toggle() {}, add() {}, remove() {} } });
    el.__q = q;
    return el;
  };
}
const roomOf = g => g.win.document.body.children.find(c => c.id === 'pvp-room');
const flush = () => new Promise(r => setTimeout(r, 30));

const ME = {
  account: { name: 'duelist', display: 'Duelist' },
  unlocks: { chars: ['runner', 'ember', 'hacker'], awake: ['ember', 'hacker'],
             chal: ['ch-sharpshooter', 'ch-pacifist'], ups: ['u1'] },
  league: { id: 'bronze', n: 'BRONZE', provisional: true },
  loadouts: {
    ranked: { pilots: ['runner', 'ember'], awake: [], ups: ['u1'] },
    casual: { pilots: ['runner', 'ember', 'hacker'], awake: ['ember', 'hacker'], ups: ['u1'] }
  }
};
const pvpScripts = PVP_SCRIPTS.map(s => ({ name: s, code: readFileSync(join(SITE, s), 'utf8') }));

/* PvP's own Worker and its referee (the Match object, pvp/src/objects.js), on
   a SQLite D1, with two players signed in. An engine signed in as one of them
   sends /api/pvp/match there, with that player's cookie; anything else goes
   to the recorder as before. */
const DB = makeD1();
const PVP_ORIGIN = 'https://voidrunner-pvp.play101.workers.dev';
const envPvp = { DB, SIGNUP: 'off', ROOM_STORE: 'voidrunner-pvp-rooms', ASSETS: { fetch: () => new Response('') } };
envPvp.MATCH = makeNamespace(Match, envPvp);
envPvp.MATCHMAKER = makeNamespace(Matchmaker, envPvp);
await ensureAuth(DB);
function signedIn(name) {
  const id = randomBytes(16).toString('hex'), token = randomBytes(32).toString('base64url'), now = Date.now();
  // a player of a while (ranked's gates: a day old, ten runs; pvp.mjs tests them)
  DB.sql.prepare('INSERT INTO accounts (id, name, display, pass, recovery, pid, perks, created, updated) VALUES (?, ?, ?, ?, ?, NULL, ?, ?, ?)')
    .run(id, name.toLowerCase(), name, '-', '-', '[]', now - 30 * 864e5, now);
  DB.sql.prepare("INSERT INTO saves (account, rev, data, unlocks, updated) VALUES (?, 1, '{\"runs\":25}', 'null', ?)").run(id, now);
  DB.sql.prepare('INSERT INTO sessions (id, account, created, seen, expires, device) VALUES (?, ?, ?, ?, ?, NULL)')
    .run(sha256(token), id, now, now, now + 30 * 864e5);
  return { id, token };
}
const DUELIST = signedIn('Duelist'), RIVAL_ACCT = signedIn('Rival');
function referee(win, who) {
  const rec = win.fetch;
  win.fetch = (u, init = {}) => {
    if (String(u) !== '/api/pvp/match') return rec(u, init);
    win.__net.push('fetch /api/pvp/match');
    return pvpWorker.fetch(new Request(PVP_ORIGIN + '/api/pvp/match', {
      method: init.method || 'GET', body: init.body,
      headers: Object.assign({}, init.headers, { cookie: 'vr_s=' + who.token, origin: PVP_ORIGIN }) }), envPvp);
  };
}
/* The page's wall clock, as game time: it moves a sixtieth of a second with
   each frame play() runs, so the referee's five-second reports come every
   five seconds of the match however fast Node plays it. The page's own Date,
   not Node's (which game-vm's window shares), so the server's clock is left
   alone. */
const WALL = { name: 'wall-clock', code: 'globalThis.__wall = Date.now(); globalThis.Date = class extends Date { static now() { return __wall; } };' };
function boot(hand, who) {
  return loadGame(IDX, {
    scripts: who ? [WALL].concat(pvpScripts) : pvpScripts,
    before: win => {
      rooms(win);
      recorder(win);
      if (who) referee(win, who);
      win.location.replace = u => { win.__replaced = u; };
      if (hand) win.sessionStorage.setItem('vr_pvp_play', JSON.stringify(hand));
    }
  });
}

section('practice: the engine boots sealed');
const g = boot({ mode: 'practice', pilot: 'hacker', me: ME });
{
  const r = code => g.run(code);
  ok(r('PVP !== null && PVP === window.VR_PVP'), 'the engine sees PvP mode');
  ok(r('state') === 'play', 'straight into play: no menu, no name prompt', r('state'));
  ok(r('P.charId') === 'hacker', 'the pilot the lobby chose', r('P.charId'));
  ok(r('P.awake') === 1, 'awake, as the account is', r('P.awake'));
  ok(r('Save.profile.name') === 'Duelist', 'the account\'s name', r('Save.profile.name'));
  ok(r('JSON.stringify(Save.profile.chal)') === JSON.stringify(ME.unlocks.chal), 'its cleared challenges, so its reward upgrades are in the pool');
  ok(r('charOpen(CHARS.find(c => c.id === "melee"))') === false, 'a pilot the account does not have is closed');
  ok(r('charOpen(CHARS.find(c => c.id === "ember"))') === true, 'one it has is open');
  // the event's own calendar says it is on: PvP mode still says no
  ok(r('HL.day = HL_EVENT.from; const live = hlLive(); HL.day = null; live') === false, 'no event, even on its dates');
  let threw = null;
  try { for (let i = 0; i < 60 * 20; i++) { r('update(1 / 60)'); if (i % 30 === 0) r('render()'); } }
  catch (e) { threw = e; }
  ok(!threw, 'twenty seconds of play, drawn, without an error', String(threw));
  await flush();
  ok(r('enemies.length') === 0 && r('wave') === 0, 'twenty seconds in: nothing has spawned', { e: r('enemies.length'), w: r('wave') });
  ok(r('state') === 'play', 'still flying', r('state'));
  ok(g.win.__net.length === 0, 'and not one request or script', g.win.__net);
  // the profile is a whole one, the game's own blank: the death screen reads its record
  ok(r('Save.profile.best === 0 && Array.isArray(Save.profile.awards)'), 'a whole blank profile, filled from the account');
  r('state = "menu"; PVP.frame()');
  ok(g.win.location.href === '/', 'leaving the run goes back to the lobby', g.win.location.href);
}

section('the same engine as the game, for contrast');
{
  const game = loadGame(IDX, { before: recorder });
  await flush();
  const net = game.win.__net;
  ok(game.run('PVP') === null, 'no PvP mode');
  ok(net.some(n => /\/api\/leaderboard/.test(n)), 'the game asks for its board: the recorder works', net);
  ok(game.run('charOpen(CHARS.find(c => c.id === "melee"))') === false && game.run('state') !== 'play',
     'and its own rules: the menu, its own unlocks');
}

section('a match: two machines, one run');
const RIVAL = Object.assign({}, ME, { account: { name: 'rival', display: 'Rival' },
  loadouts: { ranked: ME.loadouts.ranked, casual: Object.assign({}, ME.loadouts.casual, { ups: ['u2'] }) } });
/* The link, as scripts/lockstep.mjs makes it: each side's sends queued, and
   shipped across. Both say hello; the host's waiting room starts the run. */
function link(H, G) {
  for (const [g, role] of [[H, 'host'], [G, 'guest']])
    g.run(`globalThis.__out = []; netSend = function (buf) { __out.push(buf); return true; };
           Net.phase = 'live'; Net.role = '${role}'; Net.code = 'ABCD'; Net.note = '';`);
  const ship = (a, b) => { for (const d of a.run('__out.splice(0)')) { b.ctx.__msg = d; b.run('netOnMessage(__msg)'); } };
  H.run('mpOnOpen()'); G.run('mpOnOpen()'); ship(H, G); ship(G, H);
  return ship;
}
/* A bot flies this machine's own pilot at the other one: it closes in and
   circles, shoots at it, dashes, uses its kit and its awake form, and takes
   whichever card or piece of gear it is dealt. */
const BOT = `
  LS.source = rec => {
    const k = LS.hi + 1, foe = pilotP(1 - pilotMine());
    if (k % 9 === 0 && state === 'levelup' && offers.length) handleKey(String(1 + (k / 9 | 0) % offers.length));
    if (k % 9 === 0 && state === 'gear' && gearOffer) handleKey(['1', '2', 'x'][(k / 9 | 0) % 3]);
    const dx = foe.x - P.x, dy = foe.y - P.y, d = Math.hypot(dx, dy) || 1;
    const reach = P.weapon === 'laser' ? [130, 210] : P.weapon === 'blade' ? [45, 95] : [200, 430];   // its own weapon's range
    const turn = Math.floor(k / 140) % 2 ? 1 : -1, close = d > reach[1] ? 1 : d < reach[0] ? -1 : 0.2;
    const vx = close * dx / d - turn * dy / d, vy = close * dy / d + turn * dx / d;
    rec.mx = Math.abs(vx) > 0.35 ? Math.sign(vx) : 0; rec.my = Math.abs(vy) > 0.35 ? Math.sign(vy) : 0;
    const lead = P.weapon === 'bullet' ? d / (P.bspeed || 700) : 0;     // a gun leads its target, as a player would
    rec.ax = foe.x + foe.vx * lead + Math.sin(k * 0.05) * 30; rec.ay = foe.y + foe.vy * lead + Math.cos(k * 0.04) * 30;
    rec.trig = true; rec.lmb = true; rec.auto = false; rec.dash = k % 97 === 0;
    rec.touch = false; rec.taim = null; rec.press = [];
    if (k % 900 === 70) rec.press.push(P.charId === 'melee' ? 'v' : 'f');
    if (k % 75 === 40) rec.press.push(['z', 'x', 'c', 'v'][Math.floor(k / 75) % 4]);
    if (P.charId === 'melee' && k % 23 === 0) rec.press.push('f');
  };`;
/* What each machine writes down, at the end of every step of the shared
   game (the same moment on both): the match's phases, every hit one pilot
   lands on the other (hurtPlayer with opts.pvp, and what it really took),
   every card dealt, the most bullets in a shot, the room's own enemies, where
   the stand-ins wait, and a fingerprint every half second. */
const WATCH = `
  globalThis.__fp = new Map();
  globalThis.__log = { belt: null, phases: [], hits: [], room: 0, banned: [], offered: new Set(), shots: 0,
                       wildMax: 0, wildClean: 0, standOut: 0 };
  let __at = '';
  /* What a hit took is the health it left, read where the blow lands: a
     killing one meets Second Wind or a DEADMAN BRAKE (reviveOrDie), which
     stands the pilot up again with health of its own. One reading per
     hurtPlayer, innermost first, for a blow that sets off another. */
  const __hurt = hurtPlayer, __revive = reviveOrDie, __left = [];
  reviveOrDie = function () {
    if (__left.length && __left[__left.length - 1] === null) __left[__left.length - 1] = P.hp;
    return __revive.apply(this, arguments);
  };
  hurtPlayer = function (dmg, opts) {
    const m = RUN.pvp, before = P.hp, phase = m && m.phase;
    __left.push(null);
    let r, left;
    try { r = __hurt.apply(this, arguments); } finally { left = __left.pop(); }
    const after = left === null ? P.hp : left;
    if (m && opts && opts.pvp) __log.hits.push([m.clock, PILOT.on, before - Math.max(0, after), P.maxHp, phase]);
    else if (m && after < before) __log.room++;
    return r;
  };
  const __offers = k => (k === PILOT.on ? offers : PILOTS[k].v[PILOT_VARS.indexOf('offers')]) || [];
  LS.after = () => {
    const m = RUN.pvp;
    if (!m) return;
    const a = pilotP(0), b = pilotP(1);
    if (!__log.belt) __log.belt = { tick: LS.tick, state, map: m.map, maps: PVP.maps.list().length, odds: m.odds,
                                    hackers: m.hackers, infested: m.infested, bestOf: m.bestOf, lv: [a.level, b.level] };
    if (m.phase + m.round !== __at) {
      __at = m.phase + m.round;
      __log.phases.push({ tick: LS.tick, phase: m.phase, round: m.round, score: m.score.slice(), winner: m.winner,
                          loser: m.loser, lv: [a.level, b.level], owed: m.owed.slice(), clock: m.clock, state });
    }
    __log.shots = Math.max(__log.shots, PVP.shots(a), PVP.shots(b));
    for (let k = 0; k < 2; k++) for (const u of __offers(k)) { __log.offered.add(u.id); if (PVP.BANNED.has(u.id)) __log.banned.push(u.id); }
    let wild = 0;
    for (const e of enemies) {
      if (e.pvpPilot != null) { if (e.x !== -1e5 || e.y !== -1e5) __log.standOut++; }
      else if (!e.hacked) wild++;
    }
    __log.wildMax = Math.max(__log.wildMax, wild);
    if (!m.infested && wild) __log.wildClean++;
    if (LS.tick % 30 === 0)
      __fp.set(LS.tick, JSON.stringify([simRngState, m.phase, m.round, m.score, m.owed, a.charId, a.x, a.y, a.hp, a.level,
                                        b.charId, b.x, b.y, b.hp, b.level, enemies.length, bullets.length]));
  };`;
/* Both machines, a frame at a time, until `done` (or the cap); drawn now and
   then. Every half second it lets the server's answers in (the referee). */
const settle = () => new Promise(r => setImmediate(r));
async function play(H, G, ship, frames, done) {
  let i = 0;
  for (; i < frames; i++) {
    H.run('__wall += 1000 / 60; lsFrame(1 / 60); PVP.frame()'); ship(H, G);
    G.run('__wall += 1000 / 60; lsFrame(1 / 60); PVP.frame()'); ship(G, H);
    if (i % 20 === 0) { H.run('render()'); G.run('render()'); }
    if (i % 30 === 0) { await settle(); if (done && done()) break; }
  }
  return i;
}
const matchRows = () => DB.sql.prepare('SELECT * FROM pvp_matches ORDER BY ended').all();
/* art.js's hooks, called straight onto the page's canvas at a few moments
   of their life with whatever the page is showing, then a whole frame: any
   throw comes back as its message ('' for none). Straight, because a frame
   logs a hook's fault only once and draws on. */
const drawErrs = g => g.run(`(() => {
  const out = [], hook = (name, d) => { for (const t of [0, 0.3, 1, 2.5, 6]) {
    ctx.save();
    try { PVP_ART[name](ctx, W, H, t, d); } catch (e) { out.push(name + ' at ' + t + ': ' + e); } finally { ctx.restore(); } } };
  if (PVP.shown) hook('result', PVP.shown.r);
  if (PVP.preview && PVP.preview.belt) hook('belt', PVP.preview.belt);
  if (typeof RUN !== 'undefined' && RUN.pvp && !PVP.shown) hook('belt', Object.assign({ dur: PVP.ROUNDS.beltT }, PVP.maps.belt(RUN.pvp)));
  try { render(); } catch (e) { out.push('render: ' + e); }
  return out.join(' | ');
})()`);
const sameGame = (H, G) => {
  const fh = new Map(H.run('[...__fp]')), fg = new Map(G.run('[...__fp]'));
  const both = [...fh.keys()].filter(t => fg.has(t));
  return { n: both.length, parted: both.filter(t => fh.get(t) !== fg.get(t)).slice(0, 3) };
};
const DUEL = { scale: 0.22, hitCap: 0.14, burstCap: 0.34, killHit: 0.14 };
{
  const H = boot({ mode: 'match', role: 'host', pilot: 'hacker', me: ME }, DUELIST);
  const G = boot({ mode: 'match', role: 'guest', code: 'ABCD', pilot: 'ember', me: RIVAL }, RIVAL_ACCT);
  await flush();
  // Node has no WebRTC: each asked PvP's own server for its part of the link, and for nothing else
  ok(H.win.__net.join() === 'fetch /api/pvp/match,fetch /api/turn', 'the host opens its match with the referee, then asks for the relay', H.win.__net);
  ok(H.run('PVP.ref.side') === 0 && /^[0-9a-f]{32}$/.test(H.run('PVP.ref.id')), 'the referee gave it a match, as its host', H.run('[PVP.ref.id, PVP.ref.side]'));
  ok(G.win.__net[0] === 'fetch /api/room?code=ABCD&as=guest' && G.win.__net.length === 1, 'the guest looks the room up, and nothing else', G.win.__net);
  ok(H.run('state') === 'pvp' && G.run('state') === 'pvp', 'both wait in PvP\'s own room, where the run neither moves nor draws');
  const still = H.run('JSON.stringify([simTick, elapsed, waveTimer, state])');
  for (let i = 0; i < 120; i++) { H.run('update(1 / 60); render()'); H.run('handleKey("escape"); handleKey("p"); handleKey("g")'); }
  ok(H.run('JSON.stringify([simTick, elapsed, waveTimer, state])') === still, 'two seconds in the room, keys pressed: no run moves', [still, H.run('JSON.stringify([simTick, elapsed, waveTimer, state])')]);
  H.run('PVP.frame()'); G.run('PVP.frame()');
  ok(roomOf(H).__q['.line'].textContent === "Couldn't connect." && !roomOf(H).hidden, 'a link that cannot be made says so', roomOf(H).__q['.line'].textContent);
  await flush();
  ok(H.win.__net.filter(n => n === 'fetch /api/pvp/match').length === 1 && H.run('PVP.ref.until') === 0 && H.run('PVP.ref.live') === false,
     'a wait for the friend is nobody leaving: nothing said to the referee, and no clock started, until the game is on', H.win.__net);

  const ship = link(H, G);
  ok(H.run('MP.ready') && G.run('MP.ready'), 'both said hello: the same build, the same game');
  H.run('PVP.frame()');                 // the host's room sees them ready, and starts the run
  ship(H, G);
  ok(H.run('state') === 'play' && G.run('state') === 'play', 'the host started it, and the header took the guest in');
  ok(H.run('simSeed') === G.run('simSeed'), 'one run: the same seed on both');
  ok(H.run('JSON.stringify(PVP.upsOf(0))') === '["u1"]' && H.run('JSON.stringify(PVP.upsOf(1))') === '["u2"]'
     && G.run('JSON.stringify(PVP.upsOf(0))') === '["u1"]' && G.run('JSON.stringify(PVP.upsOf(1))') === '["u2"]',
     'the hellos carried each player\'s own reward upgrades, so both machines deal from the same pools',
     [H.run('JSON.stringify([PVP.upsOf(0), PVP.upsOf(1)])'), G.run('JSON.stringify([PVP.upsOf(0), PVP.upsOf(1)])')]);
  for (const g of [H, G]) g.run('PVP.frame();' + BOT + WATCH);
  ok(roomOf(H).hidden === true && roomOf(G).hidden === true, 'the waiting room steps aside');
  ok(H.run('pilotP(0).charId') === 'hacker' && H.run('pilotP(1).charId') === 'ember', 'the host flies its pilot, beside the guest\'s');
  ok(G.run('pilotP(0).charId') === 'hacker' && G.run('pilotP(1).charId') === 'ember', 'and the guest sees the same two');
  ok(H.run('pilotP(0).awake') === 1 && H.run('pilotP(1).awake') === 1, 'each awake, as its own account is');

  // the map's draw: the belt, on PvP's own screen
  await play(H, G, ship, 10);
  ok(G.run('PVP.ref.id') === H.run('PVP.ref.id') && G.run('PVP.ref.side') === 1, 'the match rode in the host\'s hello, and the guest joined it as itself',
     G.run('[PVP.ref.id, PVP.ref.side]'));
  const belt = H.run('__log.belt');
  ok(belt && belt.state === 'pvp' && G.run('state') === 'pvp', 'the match opens on the map\'s draw, on PvP\'s own screen', belt);
  ok(belt.map >= 0 && belt.map < belt.maps && belt.maps === 7, 'one of the seven sectors', belt);
  ok(belt.hackers === 1 && belt.odds === 0.75, 'one HACKER in the fight: three in four infested', belt);
  ok(belt.bestOf === 3, 'a match with a friend: best of three', belt.bestOf);
  ok(H.run('JSON.stringify(RUN.pvp)') === G.run('JSON.stringify(RUN.pvp)'), 'both drew the same map, the same way');
  let artThrew = null;
  try {
    for (const t of [0, 0.4, 1.5, 2.8, 2.9, 3.0, 3.6, 4.3, 4.8, 6])
      H.run(`PVP_ART.belt(ctx, W, H, ${t}, Object.assign({ dur: PVP.ROUNDS.beltT }, PVP.maps.belt(RUN.pvp)))`);
  } catch (e) { artThrew = e; }
  ok(!artThrew, 'the belt draws, start to finish, without an error', String(artThrew));
  const beltData = H.run('JSON.stringify(PVP.maps.belt(RUN.pvp))');
  ok(/"maps":\[\{"name":/.test(beltData) && /"infested":(true|false)/.test(beltData) && /"odds":0\.75/.test(beltData) && /"hackers":1/.test(beltData),
     'the art hook is handed every sector, the pick, the variation, the odds and why', beltData.slice(0, 200));
  // and who is fighting, from each side (match.js, M.versus)
  const bh = JSON.parse(H.run('JSON.stringify(PVP.beltData(RUN.pvp))')), bg = JSON.parse(G.run('JSON.stringify(PVP.beltData(RUN.pvp))'));
  ok(bh.me.pilot === 'hacker' && bh.them.pilot === 'ember' && bg.me.pilot === 'ember' && bg.them.pilot === 'hacker'
     && bh.me.name === 'DUELIST' && bh.them.name === 'RIVAL' && bg.me.name === 'RIVAL' && bh.me.pilotName === 'THE HACKER'
     && /^#[0-9a-f]{6}$/.test(bh.them.col) && bh.me.awake === true,
     'the belt is handed both pilots, each machine from its own side', [bh.me, bh.them, bg.me]);
  ok(bh.bestOf === 3 && bh.queue === 'friend' && bh.league === null && bh.rated === false && H.run('typeof PVP.beltData(RUN.pvp).hull') === 'function',
     'what kind of match, and the hulls to draw', [bh.bestOf, bh.queue]);
  ok(drawErrs(H) === '' && drawErrs(G) === '', 'and it draws at every moment without a fault', [drawErrs(H), drawErrs(G)]);

  // the whole match, bots at the sticks
  let threw = null, frames = 0;
  const over = () => H.run('!!(RUN.pvp && RUN.pvp.phase === "over")') && G.run('!!(RUN.pvp && RUN.pvp.phase === "over")');
  try { frames = await play(H, G, ship, 60 * 900, over); }
  catch (e) { threw = e; }
  ok(!threw, 'a whole match, drawn on both, without an error', String(threw && threw.stack));
  ok(over(), 'and it came to an end', [frames, H.run('JSON.stringify(RUN.pvp && [RUN.pvp.phase, RUN.pvp.round, RUN.pvp.score, RUN.pvp.owed])'), H.run('state')]);
  const log = H.run('__log');
  const ph = log.phases, fights = ph.filter(p => p.phase === 'fight'), ends = ph.filter(p => p.phase === 'end');
  const last = ph[ph.length - 1];
  console.log(`    (${(frames / 60).toFixed(0)} s: ${fights.length} rounds, ${last.score.join('–')}, ${log.hits.length} hits, ` +
              `${belt.infested ? 'infested, ' + log.wildMax + ' of the room\'s at most' : 'clean'}, ${log.offered.size} different cards dealt)`);

  // picks: three each, before anything else
  const firstPicks = ph.find(p => p.phase === 'picks');
  ok(firstPicks && Math.abs(firstPicks.tick - belt.tick - 288) <= 2 && firstPicks.state === 'play',
     'the belt runs its 4.8 s, then the cards', firstPicks && [firstPicks.tick - belt.tick, firstPicks.state]);
  ok(fights[0] && fights[0].lv[0] === belt.lv[0] + 3 && fights[0].lv[1] === belt.lv[1] + 3, 'three upgrades each before the first round', [belt.lv, fights[0] && fights[0].lv]);
  ok(fights.length >= 2 && fights.length <= 3 && fights.every((f, i) => f.round === i + 1), 'two or three rounds, numbered', fights.map(f => f.round));
  ok(last.phase === 'over' && Math.max(...last.score) === 2 && Math.min(...last.score) < 2 && last.score[0] + last.score[1] === fights.length,
     'best of three: the first to two rounds takes it', last.score);
  ok(ends.length === fights.length && ends.every((e, i) => e.score[0] + e.score[1] === i + 1 && e.winner === 1 - e.loser),
     'every round went to one pilot, and only one', ends.map(e => [e.winner, e.score]));
  // the loser of a round is dealt one more than the winner before the next
  const bonus = fights.slice(1).map((f, i) => {
    const prev = fights[i], l = ends[i].loser, w = ends[i].winner;
    return (f.lv[l] - prev.lv[l]) - (f.lv[w] - prev.lv[w]);
  });
  ok(bonus.length >= 1 && bonus.every(b => b === 1), 'whoever lost the round is dealt one more upgrade than the winner', bonus);
  // the clock: one more each per thirty seconds of fighting, the whole match through
  const P0 = H.run('[pilotP(0).level, pilotP(1).level]'), owed = H.run('RUN.pvp.owed.slice()'), clock = H.run('RUN.pvp.clock');
  const lost = [0, 1].map(k => ends.slice(0, -1).filter(e => e.loser === k).length);
  ok([0, 1].every(k => P0[k] + owed[k] === belt.lv[k] + 3 + Math.floor(clock / 30) + lost[k]),
     'every upgrade accounted for: three, one per thirty seconds fought, one per round lost',
     { lv: P0, owed, clock, lost, start: belt.lv });
  ok(fights.every((f, i) => (ends[i].tick - f.tick) / 60 >= 2.5), 'no round over in less than two and a half seconds',
     fights.map((f, i) => ((ends[i].tick - f.tick) / 60).toFixed(1)));

  // the hits: both ways, only in a fight, each capped, and capped together
  ok([0, 1].every(k => log.hits.some(h => h[1] === k && h[2] > 0)), 'each pilot hurt the other', [0, 1].map(k => log.hits.filter(h => h[1] === k).length));
  ok(log.hits.every(h => h[4] === 'fight'), 'and only while a round is on', log.hits.filter(h => h[4] !== 'fight').slice(0, 3));
  const big = log.hits.filter(h => h[2] > DUEL.hitCap * h[3] + 1e-6);
  ok(big.length === 0, 'no hit took more than 14% of a pilot\'s health', big.slice(0, 3));
  let worst = 0;
  for (const k of [0, 1]) {
    const hs = log.hits.filter(h => h[1] === k);
    for (const h of hs) {
      const sum = hs.filter(o => o[0] > h[0] - 1 && o[0] <= h[0]).reduce((s, o) => s + o[2], 0) / h[3];
      worst = Math.max(worst, sum);
    }
  }
  ok(worst <= DUEL.burstCap + 1e-6, 'nor all of them in any one second more than 34%', worst.toFixed(3));
  ok(log.banned.length === 0 && log.offered.size >= 6, 'not one banned card dealt, of the many that were', { banned: log.banned, n: log.offered.size });
  ok(![...log.offered].some(id => id === 'u2'), 'nor a reward upgrade that is not the pilot\'s own');
  ok(log.shots <= 4, 'never more than four bullets in a shot', log.shots);
  ok(log.standOut === 0, 'between turns both stand-ins wait off the map', log.standOut);
  // (the room sends six at most, below; a splitter's or a brood's young come on top of that)
  ok(belt.infested ? log.wildMax > 0 : log.wildMax === 0, belt.infested ? 'infested: the room sent its own' : 'clean: the room sent nothing', log.wildMax);
  ok(log.wildClean === 0, 'never an enemy of the room\'s on a clean map', log.wildClean);

  // the same game on both, start to finish
  const same = sameGame(H, G);
  ok(same.n >= 40, 'both played the same steps', same.n);
  ok(same.parted.length === 0, 'and they are the same game, step for step', same.parted);
  ok(H.run('LS.resyncs') === 0 && G.run('LS.resyncs') === 0, 'without the safety net ever needed');
  const others = g => g.win.__net.filter(n => n !== 'fetch /api/pvp/match');
  ok(others(H).join() === 'fetch /api/turn' && others(G).join() === 'fetch /api/room?code=ABCD&as=guest',
     'and not one more request but the referee\'s', [others(H), others(G)]);
  ok(H.win.__net.length > 10 && G.win.__net.length > 10, 'which heard from both all match long', [H.win.__net.length, G.win.__net.length]);

  // the referee: both machines' fingerprints held up against each other, both results, one verdict
  await play(H, G, ship, 60 * 12, () => H.run('!!PVP.ref.verdict') && G.run('!!PVP.ref.verdict'));
  const vh = H.run('PVP.ref.verdict'), vg = G.run('PVP.ref.verdict');
  ok(vh && vg && vh.v === 'played' && vg.v === 'played' && vh.winner === last.winner && vh.score.join() === last.score.join(),
     'the referee: the result stands, as both saw it', [vh, vg, last.winner, last.score]);
  const held = envPvp.MATCH.instances.get(H.run('PVP.ref.id')).data.get('m');
  ok(held.mismatch === null && held.sides.every(sd => sd.order.length >= 20 && !sd.parted),
     'having compared a fingerprint a second from each, and found them the same', held.sides.map(sd => sd.order.length));
  const row = matchRows().find(x => x.id === H.run('PVP.ref.id'));
  ok(row && row.verdict === 'played' && row.queue === 'friend' && row.a === DUELIST.id && row.b === RIVAL_ACCT.id
     && row.a_pilot === 'hacker' && row.b_pilot === 'ember' && row.winner === last.winner
     && row.score_a === last.score[0] && row.score_b === last.score[1] && row.best_of === 3,
     'recorded: who played whom, flying what, and how it went', row);
  ok(roomOf(H).__q['.note'].textContent === 'best of 3  ·  recorded' && roomOf(G).__q['.note'].textContent === 'best of 3  ·  recorded',
     'and both screens say so', [roomOf(H).__q['.note'].textContent, roomOf(G).__q['.note'].textContent]);

  // the result: the room says who won, and by how much
  const won = last.winner === 0;
  ok(!roomOf(H).hidden && roomOf(H).__q['h2'].textContent === (won ? 'VICTORY' : 'DEFEAT')
     && roomOf(G).__q['h2'].textContent === (won ? 'DEFEAT' : 'VICTORY'), 'each side is told how it went', [roomOf(H).__q['h2'].textContent, roomOf(G).__q['h2'].textContent]);
  ok(roomOf(H).__q['.line'].textContent === `DUELIST  ${last.score[0]} — ${last.score[1]}  RIVAL`
     && roomOf(G).__q['.line'].textContent === `RIVAL  ${last.score[1]} — ${last.score[0]}  DUELIST`, 'with the score, each from its own side',
     [roomOf(H).__q['.line'].textContent, roomOf(G).__q['.line'].textContent]);

  // the result screen's own picture (art.js, PVP_ART.result): what it is handed, from each side
  const shownOf = g => JSON.parse(g.run('JSON.stringify(PVP.shown && PVP.shown.r)'));
  const sh = shownOf(H), sg = shownOf(G);
  ok(sh && sg && sh.outcome === (won ? 'won' : 'lost') && sg.outcome === (won ? 'lost' : 'won')
     && sh.score.join() === last.score.join() && sg.score.join() === [last.score[1], last.score[0]].join(),
     'the result screen is handed the outcome and the score, each from its own side', [sh && sh.outcome, sg && sg.outcome]);
  ok(sh.rounds.length === last.score[0] + last.score[1] && sh.rounds.every((rd, i) => rd.won === !sg.rounds[i].won && rd.left > 0 && rd.at > 0),
     'every round in order, the other side\'s the mirror of it', [sh.rounds, sg.rounds]);
  ok(sh.me.pilot === 'hacker' && sh.them.pilot === 'ember' && sg.me.pilot === 'ember' && sh.me.pilotName === 'THE HACKER'
     && sh.me.name === 'DUELIST' && sh.them.name === 'RIVAL' && /^#[0-9a-f]{6}$/.test(sh.me.col), 'both pilots, named and coloured', [sh.me, sh.them]);
  ok(sh.dealt[0] === sg.dealt[1] && sh.dealt[1] === sg.dealt[0] && sh.dealt[0] + sh.dealt[1] > 0 && sh.time > 0
     && sh.map && sh.map.name === H.run('PVP.maps.list()[RUN.pvp.map].name') && sh.infested === belt.infested,
     'the damage each dealt, the fighting time, the map', [sh.dealt, sg.dealt, sh.time, sh.map]);
  ok(sh.queue === 'friend' && sh.rated === false && sh.league === null && sh.verdict && sh.verdict.v === 'played' && sh.verdict.won === won
     && sh.rating === null, 'a friend\'s match: the referee\'s word, and no rating', [sh.queue, sh.verdict, sh.rating]);
  ok(H.run('typeof PVP.shown.r.hull') === 'function', 'with the pilots\' hulls to draw');
  // the damage is each dealer's: what the host dealt is what the guest took, hit by hit (the log, WATCH)
  const took = k => log.hits.filter(x => x[1] === k).reduce((a, x) => a + x[2], 0);
  ok(Math.abs(sh.dealt[0] - took(1)) <= 1 && Math.abs(sh.dealt[1] - took(0)) <= 1,
     'what each dealt is what the other took, hit for hit', [sh.dealt, Math.round(took(1)), Math.round(took(0))]);
  ok(drawErrs(H) === '' && drawErrs(G) === '', 'and the screen draws without a fault', [drawErrs(H), drawErrs(G)]);
  // a verdict of no contest, arriving after the screen is up, turns it (checked on a copy: the real one is kept)
  const turned = JSON.parse(H.run(`(() => { const keep = PVP.shown; PVP.shown = { at: keep.at, r: Object.assign({}, keep.r) };
    PVP.ref.onVerdict({ v: 'void', winner: null }); const r = PVP.shown.r; PVP.shown = keep; return JSON.stringify(r); })()`));
  ok(turned.outcome === 'void' && turned.verdict.v === 'void' && turned.verdict.won === null, 'a no contest from the referee turns the screen to NO CONTEST', turned.verdict);

  // the host leaves after the end, before the guest presses BACK: the guest stays on its result (not the game's co-op screens)
  G.run('mpPeerGone(); PVP.frame()');
  ok(G.run('state') === 'pvp' && !roomOf(G).hidden && roomOf(G).__q['h2'].textContent === (won ? 'DEFEAT' : 'VICTORY'),
     'the other side leaving after the end leaves the result where it is, under its button', [G.run('state'), roomOf(G).__q['h2'].textContent]);
  G.run('render(); render()');
  ok(G.run('state') === 'pvp' && G.run('PVP.shown && PVP.shown.r.outcome') === (won ? 'lost' : 'won'), 'drawn as the result, frame after frame');

  /* The rules on their own, on the host's copy, now that the two have been
     compared: a round put back on, both pilots fresh. */
  section('the duel\'s rules, one at a time');
  const r = c => H.run('{' + c + '\n}');    // a block each, so their names stay their own
  r(`globalThis.__m = RUN.pvp; __m.phase = 'fight'; __m.hits = [[], []]; state = 'play';
     globalThis.__S = k => PVP.standIns().find(s => s.pvpPilot === k);
     globalThis.__fresh = () => { for (const k of [0, 1]) { const p = pilotP(k); p.down = false; p.hp = p.maxHp; p.iframe = 0; p.shield = 0; p.shellUp = false; p.dashT = 0; p.vx = 0; p.vy = 0; } __m.hits = [[], []]; };
     globalThis.__hp = k => pilotP(k).hp;
     PVP.as(null); __fresh();`);
  ok(r('PVP.standIns().length') === 2, 'one stand-in per pilot');
  ok(r('PVP.turn(0, () => [__S(0).x, __S(1).x === pilotP(1).x && __S(1).y === pilotP(1).y])').join() === '-100000,true',
     'on pilot 0\'s turn, its own stand-in is off the map and the other is on pilot 1');
  ok(r('__S(0).x === -1e5 && __S(1).x === -1e5'), 'and after it, both are off the map again');
  r('__fresh(); PVP.turn(0, () => damageEnemy(__S(0), 500, false, __S(0).x, __S(0).y))');
  ok(r('__hp(0) === pilotP(0).maxHp && __hp(1) === pilotP(1).maxHp'), 'a pilot never hurts itself');
  r('__fresh(); damageEnemy(__S(1), 20, false, 0, 0)');
  ok(r('__hp(1) === pilotP(1).maxHp'), 'nor does anything outside a pilot\'s turn (the room)');
  const small = r('__fresh(); PVP.turn(0, () => damageEnemy(__S(1), 20, false, 0, 0)); pilotP(1).maxHp - __hp(1)');
  const expect = r('const p = pilotP(1); Math.min(0.14 * p.maxHp, Math.max(1, 20 * 0.22 * p.frailty - p.armor * 0.22))');
  ok(small > 0 && Math.abs(small - expect) < 1e-6, 'pilot 0\'s hit on pilot 1, scaled to a pilot: 22%, through its frailty, less its armour, scaled too', [small, expect]);
  const huge = r('__fresh(); PVP.turn(0, () => damageEnemy(__S(1), 1e7, true, 0, 0)); (pilotP(1).maxHp - __hp(1)) / pilotP(1).maxHp');
  ok(huge > 0.1 && huge <= DUEL.hitCap + 1e-9, 'a hit of ten million: 14% of the pilot\'s health, no more', huge);
  const frail = r(`__fresh(); const p = pilotP(1), was = p.frailty; p.frailty = 3;
    PVP.turn(0, () => damageEnemy(__S(1), 1e7, true, 0, 0)); p.frailty = was; (p.maxHp - __hp(1)) / p.maxHp`);
  ok(frail > 0.1 && frail <= DUEL.hitCap + 1e-9, 'and on a pilot built frail (three times the damage taken): still 14%', frail);
  const burst = r(`__fresh(); for (let i = 0; i < 40; i++) { pilotP(1).iframe = 0; PVP.turn(0, () => damageEnemy(__S(1), 400, false, 0, 0)); }
                   (pilotP(1).maxHp - __hp(1)) / pilotP(1).maxHp`);
  ok(Math.abs(burst - DUEL.burstCap) < 0.01, 'forty of them in one moment: 34% in all', burst);
  const later = r(`__m.clock += 1.01; pilotP(1).iframe = 0; const was = __hp(1); PVP.turn(0, () => damageEnemy(__S(1), 400, false, 0, 0)); was - __hp(1)`);
  ok(later > 0, 'and a second later they land again', later);
  const fwd = r('__fresh(); PVP.turn(1, () => damageEnemy(__S(0), 20, false, 0, 0)); pilotP(0).maxHp - __hp(0)');
  ok(fwd > 0 && r('__hp(1) === pilotP(1).maxHp'), 'and the other way about', fwd);
  const killed = r('__fresh(); PVP.turn(0, () => killEnemy(__S(1))); (pilotP(1).maxHp - __hp(1)) / pilotP(1).maxHp');
  ok(killed > 0.1 && killed <= DUEL.killHit + 1e-9 && r('PVP.standIns().length === 2'), 'an execution lands 14% at most, and the stand-in stays', killed);
  // a killing blow that the pilot's own Second Wind or DEADMAN BRAKE answers: what it dealt is all the pilot had, as the log saw it taken
  const saved = r(`const out = [];
    for (const kind of ['revive', 'deadman']) {
      __fresh(); __m.phase = 'fight';
      const p = pilotP(1), was = [p.revive, p.deadman, p.brakeUsed, p.brakeT], d0 = __m.dealt[0], n0 = __log.hits.length;
      p.revive = kind === 'revive' ? 1 : 0; p.deadman = kind === 'deadman' ? 1 : 0; p.brakeUsed = false; p.hp = 3;
      PVP.turn(0, () => damageEnemy(__S(1), 400, false, 0, 0));
      out.push([kind, __m.dealt[0] - d0, __log.hits.slice(n0).filter(h => h[1] === 1).map(h => h[2]), !p.down && p.hp > 3 && __m.phase === 'fight']);
      [p.revive, p.deadman, p.brakeUsed, p.brakeT] = was;
    }
    out`);
  ok(saved.every(s => Math.abs(s[1] - 3) < 1e-9 && s[2].length === 1 && Math.abs(s[2][0] - 3) < 1e-9 && s[3]),
     'a killing blow that Second Wind or a DEADMAN BRAKE answers dealt all the pilot had, and the round goes on', saved);
  r(`__fresh(); for (const s of PVP.standIns()) { s.burn = 0; s.psn = 0; s.leak = 0; s.leakT = 0; }   // whatever the match left on them
     __S(1).burn = 2; __S(1).burnT = 3; __S(1).burnTick = 0; PVP.as(null)`);
  const burnt = r('for (let i = 0; i < 60; i++) PVP.dots(1 / 60); pilotP(1).maxHp - __hp(1)');
  ok(burnt > 0 && r('__hp(0) === pilotP(0).maxHp'), 'a burn on a stand-in burns its pilot, for the one who lit it', burnt);
  r('__S(1).burn = 0;');
  r('__fresh(); __m.phase = "picks"; PVP.turn(0, () => damageEnemy(__S(1), 50, false, 0, 0))');
  ok(r('__hp(1) === pilotP(1).maxHp'), 'between rounds, nothing lands');
  ok(r('pilotDo(1, () => { P.hp = 0; return PVP.down() && P.hp >= 1 && !P.down; })'), 'and nothing between rounds puts a pilot down');
  r('__fresh(); __m.phase = "fight";');
  // THE HACKER's army: a body taken on a pilot's turn is that pilot's; outside a turn, none is taken
  const army = r(`const e = spawnEnemy('grunt', arena.x0 + 100, arena.y0 + 100, { elite: false }); e.hp = 0;
                  const outside = hackTake(e);
                  const mine = pilotDo(0, () => hackTake(e)) !== false && e.hacked;
                  [outside, !!mine, e.hackPid]`);
  ok(army[0] === false, 'outside a pilot\'s turn, no body stands back up', army);
  ok(army[1] && army[2] === 0, 'one taken on THE HACKER\'s turn marches for that pilot', army);
  // set beside the rival, it goes for the rival, and what it lands counts (capped like the rest)
  const marched = r(`__fresh(); __m.hits = [[], []];
    for (let i = enemies.length - 1; i >= 0; i--) if (enemies[i].pvpPilot == null) enemies.splice(i, 1);
    const p1 = pilotP(1), e = spawnEnemy('grunt', p1.x + p1.r + 14, p1.y, { elite: false }); e.hp = 0;
    pilotDo(0, () => hackTake(e));
    const rival = pilotP(1).hp, own = pilotP(0).hp;
    for (let i = 0; i < 120; i++) { pilotP(1).iframe = 0; updateEnemies(1 / 60); PVP.as(null); e.x = pilotP(1).x + pilotP(1).r + 14; e.y = pilotP(1).y; }
    [e.hacked && e.hackPid, rival - pilotP(1).hp, own - pilotP(0).hp]`);
  ok(marched[0] === 0 && marched[1] > 0 && marched[2] === 0, 'set beside the rival, THE HACKER\'s army hurts the rival, and never its own pilot', marched);
  // a blow from inside a taken body's own script (a bomber going up, say), which the game keeps off its pilot
  const blast = r(`__fresh(); const e = enemies.find(z => z.hacked); PVP.as(0);
    const was = hackBy; hackBy = e; damageEnemy(__S(1), 40, false, 0, 0); hackBy = was; PVP.as(null);
    [!!e, pilotP(1).maxHp - __hp(1)]`);
  ok(blast[0] && blast[1] > 0, 'a blast from inside its script reaches the rival too', blast);

  // the cards
  section('the cards');
  const pool = (count, parallel, back, ids) => r(`pilotDo(0, () => { const was = [P.count, P.parallel, P.back];
    P.count = ${count}; P.parallel = ${parallel}; P.back = ${back};
    const out = PVP.cards(UPGRADES.filter(u => ${JSON.stringify(ids)}.includes(u.id))).map(u => u.id);
    [P.count, P.parallel, P.back] = was; return out.sort().join(); })`);
  ok(pool(1, 0, 0, ['multi', 'para', 'back']) === 'back,multi,para', 'one bullet a shot: more is on offer');
  ok(pool(3, 0, 0, ['multi', 'para', 'back']) === 'back,multi', 'three: a fourth, but not a second barrel (six)');
  ok(pool(2, 1, 0, ['multi', 'para', 'back']) === '', 'four: no more, of any kind');
  ok(pool(1, 0, 3, ['multi', 'para', 'back']) === '', 'four the other way (one ahead, three behind): none either');
  const banned = r('JSON.stringify([...PVP.BANNED].filter(id => UPGRADES.some(u => u.id === id)))');
  ok(pool(1, 0, 0, JSON.parse(banned)) === '', 'every banned card stays out of the pool', banned);
  ok(r('["exec", "u_unwritten"].every(id => PVP.BANNED.has(id))'), 'the instant kills first of all');
  ok(r('PVP.MAX_SHOTS') === 4, 'four bullets a shot');
  const locked = r('JSON.stringify(UPGRADES.filter(u => u.lock || u.need).map(u => u.id).slice(0, 2))');
  ok(JSON.parse(locked).length === 2 && pool(1, 0, 0, JSON.parse(locked)) === '', 'a reward upgrade the player has not earned stays out', locked);
  const outside = r(`const m = RUN.pvp; RUN.pvp = null; const out = PVP.cards(UPGRADES); RUN.pvp = m; out`);
  ok(outside === null, 'outside a match (practice) the game\'s own pool deals');
  // a level is paid only when one is owed
  ok(r(`pilotDo(0, () => { const was = [P.level, state]; __m.owed[0] = 0; P.xp = P.xpNext * 3; checkLevel();
        const out = P.level === was[0] && !offers.length && P.xp === 0; state = was[1]; return out; })`), 'experience from anything else pays nothing');

  section('the maps');
  ok(r('[PVP.maps.odds(0), PVP.maps.odds(1), PVP.maps.odds(2)].join()') === '0.5,0.75,1', 'even odds; three in four with a HACKER; always with two');
  const draw = (a, b) => r(`const was = [pilotP(0).charId, pilotP(1).charId]; pilotP(0).charId = '${a}'; pilotP(1).charId = '${b}';
    let inf = 0; const seen = new Set();
    for (let i = 0; i < 4000; i++) { const p = PVP.maps.pick(); if (p.infested) inf++; seen.add(p.index); }
    pilotP(0).charId = was[0]; pilotP(1).charId = was[1]; [inf / 4000, seen.size]`);
  const d0 = draw('runner', 'ember'), d1 = draw('ember', 'hacker'), d2 = draw('hacker', 'hacker');
  ok(Math.abs(d0[0] - 0.5) < 0.03, 'no HACKER: about half the draws infested', d0);
  ok(Math.abs(d1[0] - 0.75) < 0.03, 'one: about three in four', d1);
  ok(d2[0] === 1, 'two: every one', d2);
  ok(d0[1] === 7 && d1[1] === 7, 'and every sector comes up', [d0[1], d1[1]]);
  const spawned = inf => r(`const m = RUN.pvp, was = m.infested; m.infested = ${inf}; m.spawnT = 0;
    for (let i = enemies.length - 1; i >= 0; i--) if (enemies[i].pvpPilot == null) enemies.splice(i, 1);
    let near = 0;
    for (let i = 0; i < 60 * 60; i++) {
      const n = enemies.length; PVP.maps.spawn(m, 1 / 60);
      for (let j = n; j < enemies.length; j++) for (const k of [0, 1]) if (len(enemies[j].x - pilotP(k).x, enemies[j].y - pilotP(k).y) < 380) near++;
    }
    m.infested = was; [enemies.filter(e => e.pvpPilot == null).length, near]`);
  const sc = spawned(false), si = spawned(true);
  ok(sc[0] === 0, 'a clean map sends nothing, a minute long', sc);
  ok(si[0] === 6 && si[1] === 0, 'an infested one sends, six at most, and never on top of a pilot', si);
  ok(r(`PVP.hand.match = { bestOf: 5 }; const out = PVP.bestOf(); delete PVP.hand.match; out`) === 5,
     'a match the server made best of five (ranked, gold and up) is best of five');
  ok(r(`const was = PVP.hand.me.league; PVP.hand.me.league = { id: 'gold', bestOf: 5 }; const out = PVP.bestOf(); PVP.hand.me.league = was; out`) === 3,
     'and a match with a friend stays best of three whatever the league: the length is never this machine\'s own to say');
}

section('a match left part way');
{
  // THE VAGRANT, whose upgrades are levels and gear, against VOIDRUNNER: no HACKER, even odds
  const VAG = Object.assign({}, ME, { loadouts: { ranked: ME.loadouts.ranked, casual: { pilots: ['runner', 'melee'], awake: [], ups: [] } } });
  const H = boot({ mode: 'match', role: 'host', pilot: 'melee', me: VAG }, DUELIST);
  const G = boot({ mode: 'match', role: 'guest', code: 'ABCD', pilot: 'runner', me: RIVAL }, RIVAL_ACCT);
  await flush();
  const ship = link(H, G);
  H.run('PVP.frame()'); ship(H, G);
  for (const g of [H, G]) g.run('PVP.frame();' + BOT + WATCH);
  ok(H.run('pilotP(0).charId') === 'melee' && G.run('pilotP(0).charId') === 'melee', 'THE VAGRANT, on both');
  let threw = null;
  try { await play(H, G, ship, 60 * 120, () => H.run('RUN.pvp && RUN.pvp.round >= 1 && RUN.pvp.phase === "fight" && RUN.pvp.t > 6')); }
  catch (e) { threw = e; }
  ok(!threw, 'into the first round without an error', String(threw && threw.stack));
  const belt = H.run('__log.belt');
  ok(belt.hackers === 0 && belt.odds === 0.5, 'no HACKER: even odds', belt);
  const f = H.run('__log.phases').find(p => p.phase === 'fight');
  ok(f && f.lv[0] === belt.lv[0] + 3 && f.lv[1] === belt.lv[1] + 3, 'THE VAGRANT\'s three are levels, like the others\' cards', [belt.lv, f && f.lv]);
  const same = sameGame(H, G);
  ok(same.n >= 10 && same.parted.length === 0 && H.run('LS.resyncs') === 0, 'the same game on both', same);

  // the guest quits from the game's own pause screen; the host is told
  G.run('quitToMenu()'); ship(G, H);
  H.run('update(1 / 60); PVP.frame()'); G.run('PVP.frame()');
  ok(H.run('state') === 'pvp' && roomOf(H).__q['.line'].textContent === 'Your opponent left.', 'the host: the match is over, and why', roomOf(H).__q['.line'].textContent);
  ok(H.run('PILOTS.length') <= 1 && !H.run('LS.on'), 'its lockstep and the second pilot gone', [H.run('PILOTS.length'), H.run('LS.on')]);
  ok(G.win.location.href === '/', 'the one who quit is back in the lobby', G.win.location.href);
  ok(G.run('PVP.ref.done') === true, 'and says nothing more to the referee');

  /* The host stays, alone. The guest said it quit on its way out, so the
     host's next report hears the verdict: no grace to wait out (the Match
     object's clock is left where it is). */
  const id = H.run('PVP.ref.id');
  for (let i = 0; i < 60 * 12 && !H.run('!!PVP.ref.verdict'); i++) {
    H.run('__wall += 1000 / 60; update(1 / 60); PVP.frame()');
    if (i % 30 === 0) await settle();
  }
  const v = H.run('PVP.ref.verdict');
  ok(v && v.v === 'forfeit' && v.winner === 0, 'the referee: the guest forfeits, at once', v);
  const row = matchRows().find(x => x.id === id);
  ok(row && row.verdict === 'forfeit' && row.reason === 'quit' && row.winner === 0 && row.a_pilot === 'melee' && row.b_pilot === 'runner', 'recorded as a quit', row);
  ok(roomOf(H).__q['.note'].textContent === 'a win by forfeit  ·  recorded', 'and the host is told', roomOf(H).__q['.note'].textContent);
  const left = JSON.parse(H.run('JSON.stringify(PVP.shown.r)'));
  ok(left.outcome === 'left' && left.verdict && left.verdict.v === 'forfeit' && left.verdict.won === true
     && left.me.pilot === 'melee' && left.them.pilot === 'runner' && left.me.name === 'DUELIST',
     'its result screen: the other side went, a win by forfeit, both pilots though the second has gone', left);
}

section('a queued match: the server pairs them, and its rules fly');
{
  // the duelist's account owns EMBER awake and a reward upgrade; both have played their placements into GOLD
  const now = Date.now(), season = seasonOf(now);
  await ensurePvp(DB);
  DB.sql.prepare('INSERT OR REPLACE INTO saves (account, rev, data, unlocks, updated) VALUES (?, 1, ?, ?, ?)')
    .run(DUELIST.id, '{"runs":25}', JSON.stringify({ chars: ['runner', 'ember', 'hacker'], awake: ['ember', 'hacker'], chal: [], ups: ['u1'] }), now);
  for (const a of [DUELIST, RIVAL_ACCT])
    DB.sql.prepare(`INSERT OR REPLACE INTO pvp_ratings (account, queue, season, rating, rd, vol, games, wins, losses, league, updated)
                    VALUES (?, 'ranked', ?, 1550, 80, 0.06, 5, 3, 2, 'gold', ?)`).run(a.id, season, now);
  const rat = a => DB.sql.prepare("SELECT * FROM pvp_ratings WHERE account = ? AND queue = 'ranked' AND season = ?").get(a.id, season);
  const flagsOf = id => DB.sql.prepare('SELECT * FROM pvp_flags WHERE match = ?').all(id);
  // the lobby's part (pvp.js): queue both, and hand each engine the match the server found
  const lobby = (who, body) => pvpWorker.fetch(new Request(PVP_ORIGIN + '/api/pvp/queue', { method: 'POST', body: JSON.stringify(body),
    headers: { cookie: 'vr_s=' + who.token, origin: PVP_ORIGIN, 'content-type': 'application/json' } }), envPvp).then(r => r.json());
  const queuePair = async () => {
    await lobby(DUELIST, { op: 'join', queue: 'ranked', pilot: 'ember' });
    const g = (await lobby(RIVAL_ACCT, { op: 'join', queue: 'ranked', pilot: 'runner' })).match;
    const h = (await lobby(DUELIST, { op: 'poll', queue: 'ranked' })).match;
    return [h, g];
  };
  const bootPair = ([mh, mg]) => [
    boot({ mode: 'match', role: 'host', queue: 'ranked', pilot: 'ember', me: ME, match: mh }, DUELIST),
    boot({ mode: 'match', role: 'guest', queue: 'ranked', pilot: 'runner', me: RIVAL, match: mg }, RIVAL_ACCT)];

  const [mh, mg] = await queuePair();
  ok(mh && mg && mh.id === mg.id && mh.role === 'host' && mg.role === 'guest' && mh.league.id === 'gold' && mh.bestOf === 5,
     'the lobby queues both: one match, GOLD, best of five', mh);
  ok(mh.sides[0].pilot === 'ember' && mh.sides[0].awake === false && mh.sides[0].ups.join() === 'u1',
     'the duelist flies EMBER, not awake in GOLD though the account has it so', mh.sides[0]);
  const [H, G] = bootPair([mh, mg]);
  await flush();
  ok(H.run('PVP.ref.id') === mh.id && H.run('PVP.ref.side') === 0 && G.run('PVP.ref.id') === mh.id && G.run('PVP.ref.side') === 1,
     'both machines have the referee\'s match from the lobby: nothing opened, nothing joined');
  ok(H.run('CHARS[selectedChar].id') === 'ember' && H.run('PVP.pilotOpen("hacker")') === false, 'the host has its EMBER picked, and only that open', H.run('CHARS[selectedChar].id'));
  ok(!G.win.__net.some(n => n.startsWith('fetch /api/room')) && roomOf(G).__q.h2.textContent === 'MATCH FOUND'
     && roomOf(G).__q['.line'].textContent === 'Waiting for Duelist\'s room…', 'the guest waits for the host\'s room, with no code to type',
     [G.win.__net, roomOf(G).__q['.line'].textContent]);

  // the host's room opens (Node has no WebRTC: its code is set by hand), and the code passes through the match
  H.run("Net.phase = 'waiting'; Net.code = 'K7XQ'; Net.note = ''; PVP.frame()");
  await flush();
  ok(envPvp.MATCH.instances.get(mh.id).data.get('m').code === 'K7XQ', 'the host leaves its room\'s code with the match');
  G.run('__wall += 2000; PVP.frame()');
  await flush();
  ok(G.win.__net.includes('fetch /api/room?code=K7XQ&as=guest'), 'and the guest, asking the match, joins that room', G.win.__net);

  // the guest's hello says more than its account has: its pilot awake, every upgrade going
  G.run("Save.profile.awakened = { runner: true }; PVP.hello = () => ({ v: 1, ups: ['u1', 'u2', 'u3'] })");
  const ship = link(H, G);
  ok(H.run('MP.peerAwake') === false, 'the host takes the guest as the server has it, not as its hello says');
  H.run('PVP.frame()'); ship(H, G);
  for (const g of [H, G]) g.run('PVP.frame();' + BOT + WATCH);
  ok(H.run('pilotP(0).charId') === 'ember' && G.run('pilotP(1).charId') === 'runner'
     && [H.run('pilotP(0).awake'), H.run('pilotP(1).awake'), G.run('pilotP(0).awake'), G.run('pilotP(1).awake')].join() === '0,0,0,0',
     'both pilots on both machines as the server has them: nobody awake in GOLD');
  ok(H.run('JSON.stringify(PVP.upsOf(1))') === '[]' && G.run('JSON.stringify(PVP.upsOf(0))') === '["u1"]' && G.run('JSON.stringify(PVP.upsOf(1))') === '[]',
     'each side\'s upgrades are the server\'s, on both machines, not what a hello claims');
  ok(G.run('PVP.ref.broke') === false && H.run('PVP.ref.broke') === false, 'the start kept the rules: nothing to tell the referee');
  await play(H, G, ship, 60 * 20, () => H.run('!!RUN.pvp'));
  ok(H.run('RUN.pvp.bestOf') === 5 && G.run('RUN.pvp.bestOf') === 5, 'GOLD\'s length on both machines, from the server\'s match: best of five');

  // the guest quits: a rated forfeit, and both ratings move
  G.run('quitToMenu()'); ship(G, H);
  H.run('update(1 / 60); PVP.frame()'); G.run('PVP.frame()');
  for (let i = 0; i < 60 * 12 && !H.run('!!PVP.ref.verdict'); i++) {
    H.run('__wall += 1000 / 60; update(1 / 60); PVP.frame()');
    if (i % 30 === 0) await settle();
  }
  ok(roomOf(H).__q['.line'].textContent === 'Your opponent left.', 'the host is told its opponent left', roomOf(H).__q['.line'].textContent);
  const row = matchRows().find(x => x.id === mh.id);
  ok(row && row.queue === 'ranked' && row.rated === 1 && row.league === 'gold' && row.verdict === 'forfeit' && row.reason === 'quit'
     && row.winner === 0 && row.applied === 1, 'recorded: a rated GOLD match, the guest\'s quit, its ratings written', row);
  ok(rat(DUELIST).rating > 1550 && rat(DUELIST).wins === 4 && rat(RIVAL_ACCT).rating < 1550 && rat(RIVAL_ACCT).losses === 3,
     'up for the one who stayed, down for the one who quit', [rat(DUELIST), rat(RIVAL_ACCT)]);
  const rr = JSON.parse(H.run('JSON.stringify(PVP.shown.r)'));
  ok(rr.outcome === 'left' && rr.queue === 'ranked' && rr.rated && rr.league && rr.league.id === 'gold' && rr.bestOf === 5
     && rr.rating && rr.rating.before === 1550 && rr.rating.after === Math.round(rat(DUELIST).rating) && rr.rating.league === 'gold',
     'the host\'s result screen has its rating, before and after, once the referee wrote it', rr.rating);

  // the host walks out of the next one, and the guest is the one told it won
  const pair4 = await queuePair();
  const [H4, G4] = bootPair(pair4);
  await flush();
  const ship4 = link(H4, G4);
  H4.run('PVP.frame()'); ship4(H4, G4);
  for (const g of [H4, G4]) g.run('PVP.frame();' + BOT + WATCH);
  await play(H4, G4, ship4, 60 * 6);
  H4.run('quitToMenu()'); ship4(H4, G4);
  H4.run('PVP.frame()'); G4.run('PVP.frame()');      // the host's page sees it has quit (a frame, as a browser's next would)
  for (let i = 0; i < 60 * 12 && !G4.run('!!PVP.ref.verdict'); i++) {
    G4.run('__wall += 1000 / 60; lsFrame(1 / 60); PVP.frame()');
    if (i % 30 === 0) await settle();
  }
  const g4 = JSON.parse(G4.run('JSON.stringify(PVP.shown && PVP.shown.r)'));
  ok(roomOf(G4).__q['.note'].textContent === 'a win by forfeit  ·  recorded',
     'the guest, left alone by the host, is told it won by forfeit (its own side, though the host\'s pilot is gone)', roomOf(G4).__q['.note'].textContent);
  ok(g4 && g4.outcome === 'left' && g4.verdict.won === true && g4.me.name === 'RIVAL' && g4.me.pilot === 'runner' && g4.them.pilot === 'ember'
     && g4.rating && g4.rating.after > g4.rating.before, 'and its result screen is its own: its pilot, its win, its rating up', g4);

  // a modified host puts its own EMBER in the air awake: the guest sees the start break GOLD's rules
  const before = [rat(DUELIST).rating, rat(RIVAL_ACCT).rating];
  const pair2 = await queuePair();
  const [H2, G2] = bootPair(pair2);
  await flush();
  H2.run('Save.profile.awakened = { ember: true }');
  const ship2 = link(H2, G2);
  H2.run('PVP.frame()'); ship2(H2, G2);
  for (const g of [H2, G2]) g.run('PVP.frame();' + BOT + WATCH);
  ok(H2.run('pilotP(0).awake') === 1 && G2.run('pilotP(0).awake') === 1, 'the host flies it awake, and its start takes the guest along');
  ok(G2.run('PVP.ref.broke') === true, 'the guest sees the start break the match\'s rules');
  await play(H2, G2, ship2, 60 * 12, () => G2.run('!!PVP.ref.verdict'));
  const v2 = G2.run('PVP.ref.verdict');
  const row2 = matchRows().find(x => x.id === pair2[0].id);
  ok(v2 && v2.v === 'void' && row2 && row2.verdict === 'void' && row2.reason === 'rules' && flagsOf(pair2[0].id).length === 2,
     'at its next report: no contest, both flagged', [v2, row2]);
  ok(rat(DUELIST).rating === before[0] && rat(RIVAL_ACCT).rating === before[1], 'and no rating moves');

  // a host that never opens its room: the guest gives up after the connect time, and nothing is recorded
  const pair3 = await queuePair();
  const G3 = boot({ mode: 'match', role: 'guest', queue: 'ranked', pilot: 'runner', me: RIVAL, match: pair3[1] }, RIVAL_ACCT);
  await flush();
  G3.run('__wall += 76000; PVP.frame()');
  ok(roomOf(G3).__q.h2.textContent === 'NO MATCH' && roomOf(G3).__q['.line'].textContent === 'Duelist didn\'t connect.',
     'a guest whose host never opened a room: NO MATCH, after the connect time', roomOf(G3).__q['.line'].textContent);
  ok(G3.run('PVP.ref.done') === true && !matchRows().some(x => x.id === pair3[0].id), 'nothing more said to the referee, nothing recorded');
}

section('the art previews: /play/?preview=result and ?preview=belt');
{
  const pv = which => loadGame(IDX, { search: '?preview=' + which, scripts: pvpScripts, before: win => { rooms(win); recorder(win); } });
  const R = pv('result');
  await flush();
  ok(R.run('state') === 'pvp' && R.run('PVP.hand.mode') === 'preview' && !R.win.__replaced, 'the result preview boots on the engine, with no lobby', [R.run('state'), R.win.__replaced]);
  const r0 = JSON.parse(R.run('JSON.stringify(PVP.shown.r)'));
  ok(r0.outcome === 'won' && r0.queue === 'ranked' && r0.bestOf === 5 && r0.me.pilotName === 'THE HACKER' && r0.map && r0.map.name && r0.rounds.length === 4,
     'sample data, on the game\'s own sectors and pilots', r0);
  R.run('PVP.shown.at -= 2000; PVP.frame()');
  const r1 = JSON.parse(R.run('JSON.stringify(PVP.shown.r)'));
  ok(r1.verdict && r1.verdict.v === 'played' && r1.rating && r1.rating.after > r1.rating.before, 'the referee\'s word arrives a moment later, as in a match', r1);
  for (const k of ['lost', 'left', 'void']) {
    R.run(`PVP.previewShow('${k}')`);
    ok(R.run('PVP.shown.r.outcome') === k && drawErrs(R) === '', 'each outcome shows, and draws without a fault: ' + k);
  }
  R.run("PVP.previewShow('queue', 'casual')");
  ok(R.run('PVP.shown.r.queue') === 'casual' && R.run('PVP.shown.r.bestOf') === 3 && R.run('PVP.shown.r.league') === null, 'and casual');
  const slotOf = g => g.win.document.body.children.find(c => c.id === 'pvp-preview-slot');
  ok(slotOf(R) && slotOf(R).style.display === '', 'the match\'s button marked where it sits on the result');
  const B = pv('belt');
  await flush();
  const b0 = JSON.parse(B.run('JSON.stringify(PVP.preview.belt)'));
  ok(b0.maps.length === 7 && b0.pick >= 0 && b0.pick < 7 && b0.dur === 4.8 && drawErrs(B) === '', 'the belt preview spins the real sectors', b0);
  let fair = true;
  for (let i = 0; i < 40; i++) {
    B.run('PVP.preview.at -= 7000; PVP.frame()');
    const b = JSON.parse(B.run('JSON.stringify(PVP.preview.belt)'));
    const hackers = [b.me, b.them].filter(x => x.pilot === 'hacker').length;
    if (!b.me || !b.them || b.hackers !== hackers || b.odds !== [0.5, 0.75, 1][hackers]) fair = false;
  }
  ok(fair, 'with two sample pilots each spin, and odds that match how many are THE HACKER');
  ok(slotOf(B) && slotOf(B).style.display === 'none', 'and not on the belt, where a match has no button');
  B.run("PVP.previewShow('queue', 'casual')");
  ok(B.run('PVP.preview && PVP.preview.belt.queue') === 'casual' && B.run('PVP.preview.belt.bestOf') === 3, 'RANKED and CASUAL switch the belt too, and stay on it');
  B.run('PVP.preview.at -= 7000; PVP.frame()');
  ok(B.run('Date.now() - PVP.preview.at') < 1000, 'and starts again once it has landed');
  ok(R.win.__net.length === 0 && B.win.__net.length === 0, 'neither asks the network for anything', [R.win.__net, B.win.__net]);
}

section('arriving without the lobby');
{
  const lost = boot(null);
  ok(lost.win.__replaced === '/', 'is sent to the lobby', lost.win.__replaced);
  ok(lost.run('PVP !== null'), 'and still boots sealed while it leaves');
  await flush();
  ok(lost.win.__net.length === 0, 'and asks for nothing', lost.win.__net);
}

console.log(`\n${passes} passed, ${fails} failed  (${((Date.now() - t0) / 1000).toFixed(1)} s)`);
process.exit(fails ? 1 : 0);
