/* ===========================================================================
   THE PVP ENGINE TEST — part of `npm run test:pvp` (PVP-PLAN.md, Phase 3)

   PvP's play page is the game's own engine, copied at deploy with PvP's
   scripts in front (scripts/pvp-build.mjs). This plays that page in plain
   Node (scripts/lib/game-vm.mjs) and holds it to its promise: the engine
   boots sealed, asks no server for anything and loads no script, flies the
   account's pilot with its awake form and reward upgrades, and spawns
   nothing. The same engine booted as the game, beside it, shows the recorder
   would have caught a request.
   ========================================================================= */
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadGame, gameScript } from './lib/game-vm.mjs';
import { buildPlay, PVP_SCRIPTS } from './pvp-build.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const IDX = join(ROOT, 'index.html');
const SITE = join(ROOT, 'pvp', 'site');

let fails = 0, passes = 0;
function ok(cond, what, extra) {
  if (cond) { passes++; return; }
  fails++;
  console.log('  FAIL  ' + what + (extra !== undefined ? '  ' + JSON.stringify(extra).slice(0, 300) : ''));
}
const section = t => console.log('· ' + t);
const t0 = Date.now();

/* ---------------------------------------------------------------------- */
section('the play page, made from the game');
const html = readFileSync(IDX, 'utf8');
const page = buildPlay(html);
{
  const engine = gameScript(IDX).code;
  const scripts = [...page.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]);
  ok(scripts.length === 1, 'one inline script: the engine (the www redirect is gone)', scripts.length);
  ok(scripts[0] === engine, 'the engine, byte for byte');
  ok(!/google-adsense-account/.test(page), 'no AdSense tag');
  ok(/<title>VOIDRUNNER · PvP<\/title>/.test(page), 'its own title');
  const at = page.indexOf('<script>\n"use strict"');
  const srcs = [...page.matchAll(/<script src="([^"]+)"><\/script>/g)];
  ok(srcs.map(m => m[1]).join() === PVP_SCRIPTS.join() && srcs.every(m => m.index < at), 'PvP\'s scripts, in order, before the engine', srcs.map(m => m[1]));
  ok(/GENERATED by scripts\/pvp-build\.mjs/.test(page), 'marked as made, not written');
  let threw = null;
  try { buildPlay(html.replace('google-adsense-account', 'something-else')); } catch (e) { threw = e; }
  ok(threw && /AdSense/.test(threw.message), 'a game page it no longer recognises stops the build', String(threw));
}

/* A browser that writes down every request, and every script it is asked to load. */
function recorder(win) {
  win.__net = [];
  win.fetch = (u) => { win.__net.push('fetch ' + String(u)); return Promise.reject(new Error('offline')); };
  const make = win.document.createElement;
  win.document.createElement = tag => {
    const el = make(tag);
    if (String(tag).toLowerCase() === 'script') {
      let src = '';
      Object.defineProperty(el, 'src', { get: () => src, set: v => { src = v; win.__net.push('script ' + v); } });
    }
    return el;
  };
}
const flush = () => new Promise(r => setTimeout(r, 30));

const ME = {
  account: { name: 'duelist', display: 'Duelist' },
  unlocks: { chars: ['runner', 'ember', 'hacker'], awake: ['ember', 'hacker'],
             chal: ['ch-sharpshooter', 'ch-pacifist'], ups: ['u1'] },
  league: { id: 'bronze', n: 'BRONZE', provisional: true },
  loadouts: {
    ranked: { pilots: ['runner', 'ember'], awake: [], ups: ['u1'] },
    casual: { pilots: ['runner', 'ember', 'hacker'], awake: ['ember', 'hacker'], ups: ['u1'] }
  }
};
const pvpScripts = PVP_SCRIPTS.map(s => ({ name: s, code: readFileSync(join(SITE, s), 'utf8') }));
function boot(hand) {
  return loadGame(IDX, {
    scripts: pvpScripts,
    before: win => {
      recorder(win);
      win.location.replace = u => { win.__replaced = u; };
      if (hand) win.sessionStorage.setItem('vr_pvp_play', JSON.stringify(hand));
    }
  });
}

section('practice: the engine boots sealed');
const g = boot({ mode: 'practice', pilot: 'hacker', me: ME });
{
  const r = code => g.run(code);
  ok(r('PVP !== null && PVP === window.VR_PVP'), 'the engine sees PvP mode');
  ok(r('state') === 'play', 'straight into play: no menu, no name prompt', r('state'));
  ok(r('P.charId') === 'hacker', 'the pilot the lobby chose', r('P.charId'));
  ok(r('P.awake') === 1, 'awake, as the account is', r('P.awake'));
  ok(r('Save.profile.name') === 'Duelist', 'the account\'s name', r('Save.profile.name'));
  ok(r('JSON.stringify(Save.profile.chal)') === JSON.stringify(ME.unlocks.chal), 'its cleared challenges, so its reward upgrades are in the pool');
  ok(r('charOpen(CHARS.find(c => c.id === "melee"))') === false, 'a pilot the account does not have is closed');
  ok(r('charOpen(CHARS.find(c => c.id === "ember"))') === true, 'one it has is open');
  // the event's own calendar says it is on: PvP mode still says no
  ok(r('HL.day = HL_EVENT.from; const live = hlLive(); HL.day = null; live') === false, 'no event, even on its dates');
  let threw = null;
  try { for (let i = 0; i < 60 * 20; i++) { r('update(1 / 60)'); if (i % 30 === 0) r('render()'); } }
  catch (e) { threw = e; }
  ok(!threw, 'twenty seconds of play, drawn, without an error', String(threw));
  await flush();
  ok(r('enemies.length') === 0 && r('wave') === 0, 'twenty seconds in: nothing has spawned', { e: r('enemies.length'), w: r('wave') });
  ok(r('state') === 'play', 'still flying', r('state'));
  ok(g.win.__net.length === 0, 'and not one request or script', g.win.__net);
  // the profile is a whole one, the game's own blank: the death screen reads its record
  ok(r('Save.profile.best === 0 && Array.isArray(Save.profile.awards)'), 'a whole blank profile, filled from the account');
  r('state = "menu"; PVP.frame()');
  ok(g.win.location.href === '/', 'leaving the run goes back to the lobby', g.win.location.href);
}

section('the same engine as the game, for contrast');
{
  const game = loadGame(IDX, { before: recorder });
  await flush();
  const net = game.win.__net;
  ok(game.run('PVP') === null, 'no PvP mode');
  ok(net.some(n => /\/api\/leaderboard/.test(n)), 'the game asks for its board: the recorder works', net);
  ok(game.run('charOpen(CHARS.find(c => c.id === "melee"))') === false && game.run('state') !== 'play',
     'and its own rules: the menu, its own unlocks');
}

section('arriving without the lobby');
{
  const lost = boot(null);
  ok(lost.win.__replaced === '/', 'is sent to the lobby', lost.win.__replaced);
  ok(lost.run('PVP !== null'), 'and still boots sealed while it leaves');
  await flush();
  ok(lost.win.__net.length === 0, 'and asks for nothing', lost.win.__net);
}

console.log(`\n${passes} passed, ${fails} failed  (${((Date.now() - t0) / 1000).toFixed(1)} s)`);
process.exit(fails ? 1 : 0);
