/* ===========================================================================
   PVP'S PAGE — `node scripts/pvp-build.mjs` (PVP-PLAN.md, Phase 3)

   PvP runs the game's engine as it is. This writes pvp/site/play/index.html
   from the game's index.html:

     · the engine's script, byte for byte, so everything that reads its own
       text (the snapshot scan, buildId) works unchanged
     · PvP's own scripts in front of it (PVP_SCRIPTS), which set VR_PVP and so
       boot the engine sealed: see "PvP mode" at the top of the engine
     · the game's head extras left out: the AdSense tag and the www redirect,
       which belong to voidrunner.online

   The page is made, never edited and never committed (.gitignore). The PvP
   Worker's build runs this before every deploy (README, PvP), and so do
   `npm run dev:pvp` and `npm run test:pvp`.

   As a module, buildPlay(html) returns the page without writing it.
   ========================================================================= */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const PLAY = join(ROOT, 'pvp', 'site', 'play', 'index.html');

// PvP's own files, in the order they run: all of them before the engine
export const PVP_SCRIPTS = ['/js/mode.js', '/js/art.js', '/js/cards.js', '/js/maps.js', '/js/duel.js',
                            '/js/rounds.js', '/js/referee.js', '/js/practice.js', '/js/match.js'];

const ADS_META = /<!-- AdSense:[^\n]*-->\n<meta name="google-adsense-account"[^>]*>\n/;
const REDIRECT = /<script>\n  \/\* A save belongs to the address it was made on[\s\S]*?<\/script>\n/;
const ENGINE = /<script>\n"use strict";\n/;

export function buildPlay(html) {
  const src = html.replace(/\r\n/g, '\n');
  for (const [re, what] of [[ADS_META, 'the AdSense tag'], [REDIRECT, 'the www redirect'], [ENGINE, 'the engine']])
    if (!re.test(src)) throw new Error('pvp-build: index.html no longer has ' + what + ' where it was expected');
  const tags = PVP_SCRIPTS.map(s => `<script src="${s}"></script>`).join('\n');
  return src
    .replace('<!doctype html>\n', '<!doctype html>\n<!-- GENERATED by scripts/pvp-build.mjs from index.html. Do not edit. -->\n')
    .replace(ADS_META, '')
    .replace(REDIRECT, '')
    .replace('<title>VOIDRUNNER</title>', '<title>VOIDRUNNER · PvP</title>')
    .replace(ENGINE, `<!-- PvP's own scripts: they set VR_PVP, which boots the engine below sealed -->\n${tags}\n<script>\n"use strict";\n`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const page = buildPlay(readFileSync(join(ROOT, 'index.html'), 'utf8'));
  mkdirSync(dirname(PLAY), { recursive: true });
  writeFileSync(PLAY, page);
  console.log('pvp-build: wrote pvp/site/play/index.html (' + Math.round(page.length / 1024) + ' KB)');
}
